- alias: "HA Start"
  hide_entity: true
  trigger:
    platform: homeassistant
    event: start
  action:
    - service: notify.ios_miphone
      data_template:
        title: Home Assistant Status
        message: Started
    - service_template: frontend.set_theme
      data_template:
        name: "{% if states.sun.sun.state == \"below_horizon\" %}\n  midnight\n{% else\
          \ %}\n  default\n{% endif %}\n"
