# HomeAssistant STARTUP
- alias: 'HA Start'
  trigger:
    platform: homeassistant
    event: start
  action:
    - service: notify.ios_miphone
      data_template:
        title: "Home Assistant Status"
        message: "Started"
    - service_template: frontend.set_theme
      data_template:
        name: >
          {% if states.sun.sun.state == "below_horizon" %}
            midnight
          {% else %}
            default
          {% endif %}

# HomeAssistant SHUTDOWN
- alias: 'HA Shutdown'
  trigger:
    platform: homeassistant
    event: shutdown
  action:
    - service: notify.ios_miphone
      data_template:
        title: "Home Assistant Status"
        message: "Stopped"

# Theme Changes
- alias: 'Theme Change - Morning'
  trigger:
    - platform: state
      entity_id: sun.sun
      from: 'below_horizon'
      to: 'above_horizon'
  action:
    - service_template: frontend.set_theme
      data:
        name: default

- alias: 'Theme Change - Night'
  trigger:
    - platform: state
      entity_id: sun.sun
      from: 'above_horizon'
      to: 'below_horizon'
  action:
    - service_template: frontend.set_theme
      data:
        name: midnight


