
# https://www.home-assistant.io/components/sensor.darksky/
- platform: darksky
  api_key: !secret dark_sky_api_key
  forecast:
    - 1
    - 2
    - 3
    - 4
    - 5
  monitored_conditions:
    - summary
    - icon
    - precip_probability
    - temperature
    - apparent_temperature
    - wind_speed
    - wind_bearing
    - humidity
    - pressure
    - visibility
    - hourly_summary
    - daily_summary
    - temperature_high
    - temperature_low
    #- uv_index  # not currently being used by Lovelace weather card
## other Dark Sky conditions, none of which are being used by Lovelace weather card
    #- precip_type
    #- precip_intensity
    #- precip_accumulation
    #- precip_intensity_max
    #- dew_point
    #- minutely_summary
    #- apparent_temperature_high
    #- apparent_temperature_low
    #- moon_phase
    #- nearest_storm_distance
    #- nearest_storm_bearing
    #- wind_gust
    #- cloud_cover
    #- ozone
  update_interval:
    minutes: 5

- platform: template
  sensors:
    nextsunrise:
      friendly_name: 'Next Sunrise'
      value_template: '{{ as_timestamp(states.sun.sun.attributes.next_rising) | timestamp_custom("%a %I:%M%p") }}'

    nextsunset:
      friendly_name: 'Next Sunset'
      value_template: '{{ as_timestamp(states.sun.sun.attributes.next_setting) | timestamp_custom("%a %I:%M%p") }}'


# PocketCasts
# Currently not working: https://github.com/home-assistant/home-assistant/issues/16103
#- platform: pocketcasts
  #username: ben@benjamincharity.com
  #password: !secret pocketcasts_password

# Fast.com
- platform: fastdotcom

# Google Travel Time
- platform: google_travel_time
  id: commute-ben-work
  name: Home to work Ben
  api_key: !secret google_api_key
  origin: zone.home
  destination: zone.work_ben

- platform: google_travel_time
  id: commute-ben-home
  name: Work to home Ben
  api_key: !secret google_api_key
  origin: zone.work_ben
  destination: zone.home

# MARTA
#- platform: gtfs
  #origin: !secret marta_lindberg
  #destination: !secret marta_peachtree
  #data: marta.zip
  #name: 'MARTA Train Times'

# Plex
- platform: plex
  id: plex
  host: !secret plex_host
  token: !secret plex_token
  port: !secret plex_port


# Wemo
- platform: template
  sensors:
    wemo_energy_today:
      value_template: '{{ states.switch.wemo_insight_02.attributes["today_energy_kwh"] }}'
      friendly_name: 'Wemo Insight 02 kWh'
      unit_of_measurement: 'W'
    wemo_insight_02_cost_today:
      value_template: '{{ states.switch.wemo_insight_02.attributes["today_energy_kwh"] | multiply(0.13717) | round (2) }}'
      friendly_name: Wemo Insight 02 Cost
      unit_of_measurement: '$'
    wemo_insight_02_power:
      value_template: '{{ states.switch.wemo_insight_02.attributes["current_power_w"] }}'
      friendly_name: 'Wemo Insight 02 Power'
      unit_of_measurement: 'W'

# Crime
- platform: crimereports
  name: Home Crime Report
  radius: 1000
  latitude: !secret home_lat
  longitude: !secret home_long


- platform: template
  sensors:
    hallway_thermostat_away_mode:
      value_template: >
        {% if is_state_attr('climate.hallway', 'away_mode', 'off') %}
          Home
        {% else %}
          Away
        {% endif %}
