group:
    music_spotify:
      name: Music 
      entities:
      - input_select.spotify_playlist_ben
      - input_select.spotify_source_ben
      - script.spotify_music_ben
      - input_number.spotify_volume_ben

#Use this to find aliases for your spotify media_player component (in your configuration.yaml file).  Look at home-assistant.log to find the aliases of your components.  Enter these aliases into that component in configuration.yaml.
# https://home-assistant.io/components/media_player.spotify/
logger:
    default: warning
    logs:
        homeassistant.components.media_player.spotify: info
      
homeassistant:
  customize:
    script.spotify_music_ben:
      friendly_name: 'Play Bens Music'
      icon: mdi:play

input_number:
  spotify_volume_ben:
    name: Volume
    icon: mdi:volume-high
    min: 0
    max: 1
    step: 0.05

input_select:
  spotify_playlist_ben:
    name: 'Playlist:'
    options:
      - Your Favorite Coffehouse
      - Morning Commute
      - Cinematic Chill-Out
      - FUTURESYNTH
      - From a Smokey Bar
      - Piano in the Background
    initial: Your Favorite Coffehouse
    icon: mdi:spotify
  spotify_source_ben:
    name: 'Source:'
    options:
      - SIRFARKWAD
      - MiPhone
    initial: SIRFARKWAD
    icon: mdi:speaker-wireless

script:
    spotify_music_ben:
    #alias: Play selected spotify playlist
        sequence:
          - service: media_player.volume_set
            data:
              entity_id: media_player.bens_spotify
              volume_level: '0.40'
          -  service: media_player.select_source
             data_template: 
               entity_id: media_player.bens_spotify
               source: >
                {% if is_state("input_select.spotify_source", "SIRFARKWAD") %} SIRFARKWAD
                {% elif is_state("input_select.spotify_source", "MiPhone") %} MiPhone
                {% endif %}
          -  service: media_player.play_media
             data_template:
               entity_id: media_player.bens_spotify
               media_content_type: playlist
               media_content_id: >
                {% if is_state("input_select.spotify_playlist", "Morning Commute") %} spotify:user:spotify:playlist:37i9dQZF1DX2MyUCsl25eb
                {% elif is_state("input_select.spotify_playlist", "Cinematic Chill-Out") %} spotify:user:spotify:playlist:37i9dQZF1DWVFJtzvDHN4L
                {% elif is_state("input_select.spotify_playlist", "FUTURESYNTH") %} spotify:user:12131571557:playlist:2JgjNysZhksrtRjuGbbWns
                {% elif is_state("input_select.spotify_playlist", "From a Smokey Bar") %} spotify:user:spotify:playlist:37i9dQZF1DWTlzJXLRpd4a 
                {% elif is_state("input_select.spotify_playlist", "Piano in the Background") %} spotify:user:spotify:playlist:37i9dQZF1DX7K31D69s4M1
                {% elif is_state("input_select.spotify_playlist", "Your Favorite Coffehouse") %} spotify:user:spotify:playlist:37i9dQZF1DX6ziVCJnEm59
                {% endif %}
            
automation:
  - alias: 'Set Spotify Volume'
    trigger:
        platform: state
        entity_id: input_number.spotify_volume
    action:
        service: media_player.volume_set
        data_template:
          entity_id: media_player.bens_spotify
          volume_level: '{{  states.input_number.spotify_volume.state  }}'