- alias: "Theme Change - Night"
  hide_entity: true
  trigger:
    platform: state
    entity_id: sun.sun
    from: above_horizon
    to: below_horizon
  action:
    - service_template: frontend.set_theme
      data:
        name: midnight
