# TODO: Add condition requiring 'family' to be 'in bed' before turning off
- alias: "Turn off the porch lights at 11pm"
  trigger:
    platform: time
    hours: 23
    minutes: 00
    seconds: 00
  action:
    - service: light.turn_off
      entity_id:
        - light.front_porch_overhead_light
