- alias: "Turn on the porch light when the sun sets"
  trigger:
    platform: sun
    event: sunset
    offset: "-00:45:00"
  condition:
    condition: state
    entity_id: light.front_porch_overhead_light
    state: 'off'
  action:
    - service: light.turn_on
      entity_id:
        - light.front_porch_overhead_light
