- alias: "Turn on the carport light when motion is detected"
  trigger:
    platform: state
    entity_id: sensor.hue_motion_sensor_motion_01
    from: 'off'
    to: 'on'
  condition:
    condition: sun
    after: sunset
    after_offset: "-01:00:00"
  action:
    - service: light.turn_on
      entity_id:
        - light.garage_main_lights
      data:
        brightness_pct: 100
