- alias: "Turn on front porch light when someone is on the porch"
  trigger:
    - platform: state
      entity_id: binary_sensor.front_door_camera__porch_activity
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: binary_sensor.front_door_camera_person_detected
      from: 'off'
      to: 'on'
  condition:
    condition: state
    entity_id: sun.sun
    state: below_horizon
  action:
    - service: light.turn_on
      entity_id:
        - light.front_porch
      data:
        brightness_pct: 100
