#####################
#
# When a household member arrives home after dark
#
#####################
- alias: Location - Someone is home

  trigger:
    - platform: state
      entity_id: group.household
      from: 'away'
      to: 'home'

  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'

  action:
    service: scene.turn_on
    entity_id: scene.welcome_home
