#####################
#
# Day
#
#####################
- alias: Theme Change - Morning
  hide_entity: true
  trigger:
  - platform: state
    entity_id: sun.sun
    from: below_horizon
    to: above_horizon
  action:
  - service_template: frontend.set_theme
    data:
      name: default


#####################
#
# Night
#
#####################
- alias: Theme Change - Night
  hide_entity: true
  trigger:
  - platform: state
    entity_id: sun.sun
    from: above_horizon
    to: below_horizon
  action:
  - service_template: frontend.set_theme
    data:
      name: midnight
