#####################
#
# Washing machine
#
#####################
- alias: Alert Washing Machine
  trigger:
  - entity_id: binary_sensor.washing_machine
    platform: state
  #condition:
  #- condition: state
    #entity_id: group.family
    #state: 'on'
  action:
    # NOTE: This is currently speaking through the Apple TV
    - service: tts.google_say
      data:
        message: "The washing machine has finished."
