nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret
  sensors:
    monitored_conditions:
      - 'operation_mode'
      - 'security_state'
      - 'eta'
      - 'temperature'
      - 'target'
      - 'hvac_state'


#####################
# Sensors
#####################
sensor:
  # Thermostat Away Mode
  - platform: template
    sensors:
      hallway_thermostat_away_mode:
        value_template: >
          {% if is_state_attr('climate.hallway', 'away_mode', 'off') %}
            Home
          {% else %}
            Away
          {% endif %}
