homeassistant:
  customize:
    sensor.hue_motion_sensor_motion_01:
      friendly_name: Carport Motion
      icon: mdi:eye
      hidden: true
    sensor.guest_switch:
      friendly_name: Guest Light Switch
      icon: mdi:light-switch
      hidden: true

hue:
  bridges:
    - host: !secret hue_bridge_ip

device_tracker:
  - platform: hue

sensor:
  - platform: hue
